# Generated by Django 5.0.6 on 2024-06-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_alter_book_author_alter_book_book_alter_book_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='mebimage',
        ),
    ]
