# Generated by Django 5.0.6 on 2024-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_rename_image_member_mebimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
