# Generated by Django 5.0.6 on 2024-06-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_borrower_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='returned',
            field=models.CharField(default='No', max_length=255),
        ),
    ]
